(function() {var implementors = {};
implementors['cocoa'] = ["<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitOr.html' title='core::ops::BitOr'>BitOr</a> for <a class='struct' href='cocoa/appkit/struct.NSWindowOrderingMode.html' title='cocoa::appkit::NSWindowOrderingMode'>NSWindowOrderingMode</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitOr.html' title='core::ops::BitOr'>BitOr</a> for <a class='struct' href='cocoa/appkit/struct.NSAlignmentOptions.html' title='cocoa::appkit::NSAlignmentOptions'>NSAlignmentOptions</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitOr.html' title='core::ops::BitOr'>BitOr</a> for <a class='struct' href='cocoa/appkit/struct.NSWindowCollectionBehavior.html' title='cocoa::appkit::NSWindowCollectionBehavior'>NSWindowCollectionBehavior</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitOr.html' title='core::ops::BitOr'>BitOr</a> for <a class='struct' href='cocoa/appkit/struct.NSWindowOcclusionState.html' title='cocoa::appkit::NSWindowOcclusionState'>NSWindowOcclusionState</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitOr.html' title='core::ops::BitOr'>BitOr</a> for <a class='struct' href='cocoa/appkit/struct.NSEventSwipeTrackingOptions.html' title='cocoa::appkit::NSEventSwipeTrackingOptions'>NSEventSwipeTrackingOptions</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitOr.html' title='core::ops::BitOr'>BitOr</a> for <a class='struct' href='cocoa/appkit/struct.NSEventPhase.html' title='cocoa::appkit::NSEventPhase'>NSEventPhase</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitOr.html' title='core::ops::BitOr'>BitOr</a> for <a class='struct' href='cocoa/appkit/struct.NSTouchPhase.html' title='cocoa::appkit::NSTouchPhase'>NSTouchPhase</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitOr.html' title='core::ops::BitOr'>BitOr</a> for <a class='struct' href='cocoa/appkit/struct.NSEventMask.html' title='cocoa::appkit::NSEventMask'>NSEventMask</a>","<a class='stability Stable' title='Stable'></a>impl <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.BitOr.html' title='core::ops::BitOr'>BitOr</a> for <a class='struct' href='cocoa/appkit/struct.NSEventModifierFlags.html' title='cocoa::appkit::NSEventModifierFlags'>NSEventModifierFlags</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
